package com.cn.speedchat.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.cn.speedchat.greendao.ReplayEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table REPLAY_ENTITY.
*/
public class ReplayEntityDao extends AbstractDao<ReplayEntity, Long> {

    public static final String TABLENAME = "REPLAY_ENTITY";

    /**
     * Properties of entity ReplayEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Mode = new Property(1, int.class, "mode", false, "MODE");
        public final static Property From = new Property(2, String.class, "from", false, "FROM");
        public final static Property To = new Property(3, String.class, "to", false, "TO");
        public final static Property V_code = new Property(4, String.class, "v_code", false, "V_CODE");
        public final static Property Timestamp = new Property(5, String.class, "timestamp", false, "TIMESTAMP");
        public final static Property Platform = new Property(6, String.class, "platform", false, "PLATFORM");
        public final static Property Message = new Property(7, String.class, "message", false, "MESSAGE");
        public final static Property Msgtype = new Property(8, int.class, "msgtype", false, "MSGTYPE");
        public final static Property Isread = new Property(9, boolean.class, "isread", false, "ISREAD");
    };


    public ReplayEntityDao(DaoConfig config) {
        super(config);
    }
    
    public ReplayEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'REPLAY_ENTITY' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'MODE' INTEGER NOT NULL ," + // 1: mode
                "'FROM' TEXT NOT NULL ," + // 2: from
                "'TO' TEXT NOT NULL ," + // 3: to
                "'V_CODE' TEXT," + // 4: v_code
                "'TIMESTAMP' TEXT NOT NULL ," + // 5: timestamp
                "'PLATFORM' TEXT," + // 6: platform
                "'MESSAGE' TEXT," + // 7: message
                "'MSGTYPE' INTEGER NOT NULL ," + // 8: msgtype
                "'ISREAD' INTEGER NOT NULL );"); // 9: isread
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'REPLAY_ENTITY'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ReplayEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getMode());
        stmt.bindString(3, entity.getFrom());
        stmt.bindString(4, entity.getTo());
 
        String v_code = entity.getV_code();
        if (v_code != null) {
            stmt.bindString(5, v_code);
        }
        stmt.bindString(6, entity.getTimestamp());
 
        String platform = entity.getPlatform();
        if (platform != null) {
            stmt.bindString(7, platform);
        }
 
        String message = entity.getMessage();
        if (message != null) {
            stmt.bindString(8, message);
        }
        stmt.bindLong(9, entity.getMsgtype());
        stmt.bindLong(10, entity.getIsread() ? 1l: 0l);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public ReplayEntity readEntity(Cursor cursor, int offset) {
        ReplayEntity entity = new ReplayEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // mode
            cursor.getString(offset + 2), // from
            cursor.getString(offset + 3), // to
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // v_code
            cursor.getString(offset + 5), // timestamp
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // platform
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // message
            cursor.getInt(offset + 8), // msgtype
            cursor.getShort(offset + 9) != 0 // isread
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ReplayEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMode(cursor.getInt(offset + 1));
        entity.setFrom(cursor.getString(offset + 2));
        entity.setTo(cursor.getString(offset + 3));
        entity.setV_code(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setTimestamp(cursor.getString(offset + 5));
        entity.setPlatform(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setMessage(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setMsgtype(cursor.getInt(offset + 8));
        entity.setIsread(cursor.getShort(offset + 9) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(ReplayEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(ReplayEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
