package com.cn.speedchat.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table REPLAY_ENTITY.
 */
public class ReplayEntity {

    private Long id;
    private int mode;
    /** Not-null value. */
    private String from;
    /** Not-null value. */
    private String to;
    private String v_code;
    /** Not-null value. */
    private String timestamp;
    private String platform;
    private String message;
    private int msgtype;
    private boolean isread;

    public ReplayEntity() {
    }

    public ReplayEntity(Long id) {
        this.id = id;
    }

    public ReplayEntity(Long id, int mode, String from, String to, String v_code, String timestamp, String platform, String message, int msgtype, boolean isread) {
        this.id = id;
        this.mode = mode;
        this.from = from;
        this.to = to;
        this.v_code = v_code;
        this.timestamp = timestamp;
        this.platform = platform;
        this.message = message;
        this.msgtype = msgtype;
        this.isread = isread;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getMode() {
        return mode;
    }

    public void setMode(int mode) {
        this.mode = mode;
    }

    /** Not-null value. */
    public String getFrom() {
        return from;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFrom(String from) {
        this.from = from;
    }

    /** Not-null value. */
    public String getTo() {
        return to;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTo(String to) {
        this.to = to;
    }

    public String getV_code() {
        return v_code;
    }

    public void setV_code(String v_code) {
        this.v_code = v_code;
    }

    /** Not-null value. */
    public String getTimestamp() {
        return timestamp;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTimestamp(String timestamp) {
        this.timestamp = timestamp;
    }

    public String getPlatform() {
        return platform;
    }

    public void setPlatform(String platform) {
        this.platform = platform;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public int getMsgtype() {
        return msgtype;
    }

    public void setMsgtype(int msgtype) {
        this.msgtype = msgtype;
    }

    public boolean getIsread() {
        return isread;
    }

    public void setIsread(boolean isread) {
        this.isread = isread;
    }

}
